# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(948, 554)
        Dialog.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 180, 441, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.monitor = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.monitor.setFont(font)
        self.monitor.setObjectName("monitor")
        self.verticalLayout.addWidget(self.monitor)
        self.classify = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.classify.setFont(font)
        self.classify.setObjectName("classify")
        self.verticalLayout.addWidget(self.classify)
        self.warning = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.warning.setFont(font)
        self.warning.setObjectName("warning")
        self.verticalLayout.addWidget(self.warning)
        self.record = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.record.setFont(font)
        self.record.setObjectName("record")
        self.verticalLayout.addWidget(self.record)
        self.exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.verticalLayout.addWidget(self.exit)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(370, 60, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.record.clicked.connect(Dialog.record) # type: ignore
        self.warning.clicked.connect(Dialog.warning) # type: ignore
        self.classify.clicked.connect(Dialog.classify) # type: ignore
        self.monitor.clicked.connect(Dialog.monitor) # type: ignore
        self.exit.clicked.connect(Dialog.exit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.monitor.setText(_translate("Dialog", "实时检测"))
        self.classify.setText(_translate("Dialog", "障碍物分类"))
        self.warning.setText(_translate("Dialog", "风险预警"))
        self.record.setText(_translate("Dialog", "沿途记录"))
        self.exit.setText(_translate("Dialog", "退出"))
        self.label.setText(_translate("Dialog", "功能菜单"))

