# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_register_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginRegister(object):
    def setupUi(self, LoginRegister):
        LoginRegister.setObjectName("LoginRegister")
        LoginRegister.resize(400, 300)
        self.tabWidget = QtWidgets.QTabWidget(LoginRegister)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 380, 280))
        self.tabWidget.setObjectName("tabWidget")
        self.loginTab = QtWidgets.QWidget()
        self.loginTab.setObjectName("loginTab")
        self.label = QtWidgets.QLabel(self.loginTab)
        self.label.setGeometry(QtCore.QRect(30, 30, 71, 21))
        self.label.setObjectName("label")
        self.loginUsername = QtWidgets.QLineEdit(self.loginTab)
        self.loginUsername.setGeometry(QtCore.QRect(110, 30, 200, 21))
        self.loginUsername.setObjectName("loginUsername")
        self.label_2 = QtWidgets.QLabel(self.loginTab)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 71, 21))
        self.label_2.setObjectName("label_2")
        self.loginPassword = QtWidgets.QLineEdit(self.loginTab)
        self.loginPassword.setGeometry(QtCore.QRect(110, 70, 200, 21))
        self.loginPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPassword.setObjectName("loginPassword")
        self.loginButton = QtWidgets.QPushButton(self.loginTab)
        self.loginButton.setGeometry(QtCore.QRect(110, 110, 200, 32))
        self.loginButton.setObjectName("loginButton")
        self.tabWidget.addTab(self.loginTab, "")
        self.registerTab = QtWidgets.QWidget()
        self.registerTab.setObjectName("registerTab")
        self.label_3 = QtWidgets.QLabel(self.registerTab)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 71, 21))
        self.label_3.setObjectName("label_3")
        self.registerUsername = QtWidgets.QLineEdit(self.registerTab)
        self.registerUsername.setGeometry(QtCore.QRect(110, 30, 200, 21))
        self.registerUsername.setObjectName("registerUsername")
        self.label_4 = QtWidgets.QLabel(self.registerTab)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 71, 21))
        self.label_4.setObjectName("label_4")
        self.registerPassword = QtWidgets.QLineEdit(self.registerTab)
        self.registerPassword.setGeometry(QtCore.QRect(110, 70, 200, 21))
        self.registerPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registerPassword.setObjectName("registerPassword")
        self.registerButton = QtWidgets.QPushButton(self.registerTab)
        self.registerButton.setGeometry(QtCore.QRect(110, 110, 200, 32))
        self.registerButton.setObjectName("registerButton")
        self.tabWidget.addTab(self.registerTab, "")

        self.retranslateUi(LoginRegister)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginRegister)

    def retranslateUi(self, LoginRegister):
        _translate = QtCore.QCoreApplication.translate
        LoginRegister.setWindowTitle(_translate("LoginRegister", "Login/Register"))
        self.label.setText(_translate("LoginRegister", "Username:"))
        self.label_2.setText(_translate("LoginRegister", "Password:"))
        self.loginButton.setText(_translate("LoginRegister", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loginTab), _translate("LoginRegister", "Login"))
        self.label_3.setText(_translate("LoginRegister", "Username:"))
        self.label_4.setText(_translate("LoginRegister", "Password:"))
        self.registerButton.setText(_translate("LoginRegister", "Register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.registerTab), _translate("LoginRegister", "Register"))
